name: Jaguar Health
favicon: null
layout_spectrum: 0.23132578819058836
typography_spectrum: 0.8888031598180532
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.01846316084265709
  lightness: 0.13484985497780144
  saturation: 0.20488622318953276
  rhythmicContrast: 0.019188130041584373
purpose: []
