typography_spectrum: 0.13275
color:
  brandColors:
    - '#47342d'
    - '#26150d'
    - '#537423'
    - '#a9866a'
    - '#bebb97'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99806
analytics:
  google: null
  facebook: null
  twitter: null
name: Jaguar Health
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Jaguar Health
description: healing you = saving the rainforest
purpose: []
