name: Jaguar Health
favicon: null
layout_spectrum: 0.23132578819058836
typography_spectrum: 0.8888031598180532
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff1e1a'
    - '#00f750'
    - '#1b0323'
    - '#00aef8'
    - '#fef452'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
